print ("Controle de Estoque básico")
print (". . . . .")
print ("Cadastro básico")
cad = input("Digite o produto: ")
qtde = input("Digite a quantidade: ")
valor = input("Digite o valor: ")
print (". . . . .")
print ("Produtos cadastrados:")
print (f"Produto: " + cad)
print (f"Quantidade: " + qtde)
print (f"Valor: R$ " + valor)
print (". . . . .")
print ("Fim do programa")